Update tti_61f59e574f9f7babfe8908e5.json
vitelabs/crypto-info pull request #49
Opened 2020-08-25 18:35 UTC by sebrock

Line 11: Corrected spelling of 'discord' and updated discord invite link.

2020-08-26 00:12 UTC, l33d4n reviewed
You did not follow the submission guideline:

- uptrennd - Does not support
- TikTok - Does not support
- BitcoinTalk - Does not support

Vite Token Profile Submission Guideline: https://github.com/vitelabs/crypto-info/blob/master/tokens/vite-tutorial.en.md

2020-08-26 06:59 UTC, sebrock commented
> You did not follow the submission guideline:
> 
> 
> 
> - uptrennd - Does not support
> 
> - TikTok - Does not support
> 
> - BitcoinTalk - Does not support
> 
> 
> 
> Vite Token Profile Submission Guideline: https://github.com/vitelabs/crypto-info/blob/master/tokens/vite-tutorial.en.md

Thanks for letting me know. I'll correct and resubmit.

2020-08-26 19:13 UTC, sebrock commented
Corrected BAN as per contribution guide. @l33d4n would you mind reviewing and merging? thanks!

2020-08-26 23:12 UTC, l33d4n approved these changes

2020-08-26 23:12 UTC, l33d4n commented on tokens/ban/tti_61f59e574f9f7babfe8908e5.json
>          "youtube":["https://www.youtube.com/c/BananoPictures],
```suggestion
        "youtube":["https://www.youtube.com/c/BananoPictures"],
```

2020-08-26 23:14 UTC, l33d4n requested changes

2020-08-26 23:14 UTC, l33d4n commented on tokens/ban/tti_61f59e574f9f7babfe8908e5.json
> +        "youtube":["https://www.youtube.com/c/BananoPictures],
```suggestion
        "youtube":["https://www.youtube.com/c/BananoPictures"],
```

2020-08-26 23:17 UTC, l33d4n commented
@sebrock Looks good, just need to add " to the end of the Youtube link

2020-08-27 08:31 UTC, sebrock commented
> @sebrock Looks good, just need to add " to the end of the Youtube link

Done. Thanks!

2020-08-27 08:37 UTC, l33d4n approved these changes

2020-08-27 10:01 UTC, merged